// Generated by CoffeeScript 1.6.3
(function() {
  var fs, walk;

  fs = require('fs');

  walk = function(dir) {
    var file, list, res, results, stat, _i, _len;
    results = [];
    list = fs.readdirSync(dir);
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      file = list[_i];
      file = dir + '/' + file;
      stat = fs.statSync(file);
      if (stat && stat.isDirectory()) {
        res = walk(file);
        results = results.concat(res);
      } else {
        results.push(file);
      }
    }
    return results;
  };

  module.exports = walk;

}).call(this);
