// Generated by CoffeeScript 1.6.3
(function() {
  var globalize;

  globalize = require("../tasks/globalize-html");

  globalize.globalize("tests/views/res", "tests/views/src", "tests/views/");

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
